# Generated by Django 3.0.7 on 2020-06-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='opcion_t',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
