# Generated by Django 3.0.7 on 2020-06-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_auto_20200620_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=24)),
                ('fecha', models.DateTimeField()),
                ('apellidos', models.CharField(max_length=24)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('sugerencia', models.TextField(max_length=200)),
                ('opcion1', models.TextField(max_length=24)),
                ('opcion2', models.TextField(max_length=24)),
                ('opcion3', models.TextField(max_length=24)),
            ],
        ),
    ]
