# Generated by Django 3.0.7 on 2020-06-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_sugerencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sugerencia',
        ),
    ]
