# Generated by Django 3.0.7 on 2020-06-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_sugerencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sugerencia',
        ),
    ]
